### ISSUE TITLE
user.get_permissions breaks for admin user from zope-root acl_users

### ISSUE THREAD

**Issue by thet** [plone/plone.api#157]
when using `plone.api.user.get_permissions(user=user)` with the admin user from zope-root's acl_users folder, it breaks with a `UserNotFoundError`.
looks like the reason can be found here: https://github.com/plone/plone.api/blob/16bc0c731f5f55ac2fbed63852296c488e3c2796/src/plone/api/env.py#L39
the basic zope admin user cant be found in Plone's acl_users

**Comment by jaroel** [comment]
This should be fixed in #209
