### ISSUE TITLE
Helpful workflow feature

### ISSUE THREAD

**Issue by adamcheasley** [plone/plone.api#162]
We have some code here at Netsight, and we're wondering if it's something that others might find useful and whether it could go into the api.

Essentially, what the code does is take an object and two workflow states. It then tries to transition the object from one state to the other, regardless of how many states are in  between. This is especially useful when you a complex workflow. It's also useful in tests, when you just want to put an object in a state, and you don't care too much how to get it there.

Is this a feature anyone else would be interested in?

**Comment by jaroel** [comment]
What needs to be done, and who is going to do it?

**Comment by adamcheasley** [comment]
Nothing needs to be done. I've already implemented the feature.
