### ISSUE TITLE
Do we *need* to list Plone as a dependency?

### ISSUE THREAD

**Issue by zupo** [plone/plone.api#165]
The ``mutually_exclusive_parameters`` and other decorators in validation.py are a honking great idea and I want to use them in non-Plone projects also! 

However if my non-Plone project depends on plone.api, then all Plone packages get pulled in due to the fact that plone.api lists Plone as an install dependency in plone.api.

What pitfalls wait for us if we remove Plone as an install dependency to allow usage of certain parts of it outside of Plone-specific codebases?

**Comment by jaroel** [comment]
We don't have a dependency on Plone after #180 .
An alternative is to extract that functionality into a seperate package, or collaborate to extend existing solutions like pyvalid

**Comment by gforcada** [comment]
:+1: on reusing/extending other solutions, we surely are not the first ones to come with that and lots of other projects would benefit from that too!
