### ISSUE TITLE
Prepare for inclusion and usage in Plone Core

### ISSUE THREAD

**Issue by zupo** [plone/plone.api#180]
During the PloneConf 2014 open-spaces it was decided that we should try to get plone.api included and used in Plone Core. Here are our notes:
- ship plone.api as a core package
- all core packages are allowed to use plone.api in tests
- a core package is allowed to use plone.api only if plone.api does not depend on it (to prevent circular dependencies and tightly coupled code)
- in order to be able to respect the above rule, plone.api needs remove its dependency on the "Plone" package and rather specify actual dependencies in its setup.py
- besides this, plone.api needs to keep an auto-updated list of all of its dependencies and dependencies of these dependencies so core committers can quickly see if the package they are working on is allowed to use plone.api or not
- to ensure the "plone.api usage in core" rule, we need a Jenkins job that checks that no blacklisted packages use plone.api

**Comment by jaroel** [comment]
I need someone to make the tests work in buildout.coredev.

**Comment by gforcada** [comment]
@jaroel which tests do you mean?

**Comment by jaroel** [comment]
The Plone 5 job on travis. When that works, the plip tests should run too.

**Comment by jaroel** [comment]
plone.api is now tested in Plone 5 on travis-ci, and there's a PLIP job on jenkins.plone.org/view/PLIPs/job/plip-20114-plone.api-integration/.

**Comment by jaroel** [comment]
Someone needs to check all functions and make sure they are consisted and correct, ie userid vs username, groupid vs groupname.

**Comment by jaroel** [comment]
#204 is a blocker for this.

**Comment by jaroel** [comment]
The workaround with getting the user and passing it in is acceptable to me.

**Comment by jaroel** [comment]
plone.api is added as a dependency for Products.CMFPlone. https://github.com/plone/Products.CMFPlone/pull/873

**Comment by zupo** [comment]
:beers:

**Comment by tisto** [comment]
Awesome!!! Though, the build is broken now. http://jenkins.plone.org/job/plone-5.0-python-2.7/2358/changes#detail0

**Comment by jaroel** [comment]
I noticed.

**Comment by jaroel** [comment]
Reverted the merge for now. https://github.com/plone/Products.CMFPlone/commit/3f5cb67550c8f105dc4c701e9941030195310c21

**Comment by jaroel** [comment]
And we're green again: http://jenkins.plone.org/job/plone-5.0-python-2.7/2368/

**Comment by jaroel** [comment]
A big thank you to everyone involved! This has been in the works since at least 2012 :)
