### ISSUE TITLE
Disallow 1-letter vars

### ISSUE THREAD

**Issue by jensens** [plone/plone.api#188]
I propose to disallow one letter variables. Major reasons are:

1) pdb overrides local variables. so if in pdb and variable c was defined, continue does work, but you never get the value of c *(updated: i confused the direction here)*

    >>> import pdb
    >>> c = 1
    >>> pdb.set_trace()
    --Return--
    > <stdin>(1)<module>()->None
    (Pdb) c
    >>> 

2) one-letter variables are not verbose.

In list-/dict-/tuple-/set- comprehensions one letter variables are allowed, since theres no pdb possible.

**Comment by WouterVH** [comment]
this should work as well
> print c

**Comment by jaroel** [comment]
What needs to be done, and who is going to do it?

**Comment by gforcada** [comment]
Closing this as https://github.com/plone/plone.recipe.codeanalysis/issues/100 already exists.

**Comment by tomgross** [comment]
Just for completenes, you can do a print in pdb too
```
>>> import pdb
>>> c = 1
>>> pdb.set_trace()
>>> print(c)
1
```
