### ISSUE TITLE
``make docs`` broken

### ISSUE THREAD

**Issue by jensens** [plone/plone.api#194]
jensens@minime:~/workspace/plone.api$ make docs
    bin/buildout 
    Develop: '/home/jensens/workspace/plone.api/.'
    [...]
    Install Git pre-commit hook.
    bin/sphinx-build -W docs docs/html
    Running Sphinx v1.1.3
    loading translations [en]... locale not available
    loading pickled environment... done
    No builder selected, using default: html
    building [html]: targets for 19 source files that are out of date
    updating environment: [config changed] 19 added, 0 changed, 0 removed
    reading sources... [100%] user                                                                                                                    
    looking for now-outdated files... none found
    pickling environment... done
    checking consistency... 
    Warning, treated as error:
    /home/jensens/workspace/plone.api/docs/CHANGES.rst:: WARNING: document isn't included in any toctree

    make: *** [docs/html/index.html] Error 1

**Comment by jaroel** [comment]
Please review.
