### ISSUE TITLE
Add conditional support for Archetypes

### ISSUE THREAD

**Issue by gforcada** [plone/plone.api#197]
I just saw that ``plone.api.content`` imports ``Products.Archetypes``.

As plone.api is going into core, it should have a soft-dependency on it (i.e. depend on it as an extra ``extras_require`` in ``setup.py``) and import it conditionally, i.e. http://docs.plone.org/external/plone.api/docs/contribute/conventions.html#about-imports 4th point

**Comment by jaroel** [comment]
Please review.
