### ISSUE TITLE
Move references  from api.plone.org to docs.plone.org?

### ISSUE THREAD

**Issue by gforcada** [plone/plone.api#202]
I quickly grepped and saw that there are references to api.plone.org, should they be moved to docs.plone.org?

I see that #130 was created for moving from RTD to api.plone.org, but given that docs.plone.org is in a healthy and good shape, should we move everything there?

Just wondering...

**Comment by jaroel** [comment]
api.plone.org already points to docs.plone.org, so yes :)
Could you check/merge #239?
