### ISSUE TITLE
Add content.find or content.query

### ISSUE THREAD

**Issue by jaroel** [plone/plone.api#210]
I'd like to abstract away portal_catalog by mapping portal_catalog.\__call__ to content.query or content.find.

So
```python
documents = api.content.find(portal_type='Document')
```
instead of
```python
catalog = api.portal.get_tool(name='portal_catalog')
documents = catalog(portal_type='Document')
```

We can also include context, as in 'find within this context'
```python
documents = api.content.find(portal_type='Document', context=self.context)
```

Please discuss :)

**Comment by adamcheasley** [comment]
+1
I like this idea. I think api.content.find is the perfect place for it. Would we pass all keyword arguments through to the catalog? e.g. I have a custom index and I want search based on that, like so:
```
my_objects = api.content.find(portal_type="my.type", my_index=True)
```

**Comment by gforcada** [comment]
:+1: on both p.a.find and custom indexes to be also being used!

**Comment by jaroel** [comment]
Is is just a wrapper for the catalog, so *args and **kwargs should be passed to __call__ directly.
All functionality for catalog(*args, **kwargs) or catalog(my_dict) should work as expected.

**Comment by davisagli** [comment]
Does it do a searchResults or unrestrictedSearchResults? What if I want the other one?

**Comment by adamcheasley** [comment]
IMO it would do a searchResults. This is what I use probably 90% of the time. To do an unrestricted, I think you should still have to look up the portal_catalog with get_tool and call it there.

**Comment by jaroel** [comment]
To bypass permission checks:
```python
with api.env.adopt_roles('Manager'):
    api.content.find(portal_type='Document')
```
Or
```python
catalog = api.portal.get_tool('portal_catalog')
catalog.unrestrictedSearchResults()
```

**Comment by gforcada** [comment]
The first approach (context manager) looks way more easy to understand for non-ploners IMO, looks way more pythonic and at the end it already self-documents itself that the results you will get from find are the objects that a manager can see.

Big :+1: !

**Comment by jaroel** [comment]
It doesn't skip the expiration dates, though I think that's an edge case and out of scope.

**Comment by davisagli** [comment]
Okay, those are both fine options for the unrestricted case. @jaroel I think the effective range filter can be bypassed by passing show_inactive=True if the user has the "View inactive content" permission

**Comment by jaroel** [comment]
@davisagli show_all=1 and show_inactive=1: https://www.fourdigits.nl/blog/listing-expired-plone-content

I'll draft a first implementation.

**Comment by hvelarde** [comment]
:+1:

**Comment by jaroel** [comment]
This is implemented and merged.
