### ISSUE TITLE
Reconsider pkg_resources.DistributionNotFound

### ISSUE THREAD

**Issue by gforcada** [plone/plone.api#217]
@davisagli has made a point (and some numbers) regarding catching ``pkg_resources.DistributionNotFound`` being way slower than an ``ImportError``.

The styleguide clearly says the former, but should we reconsider it due to its slowness?

**Comment by adamcheasley** [comment]
From looking at these numbers, I say we reconsider.

**Comment by hvelarde** [comment]
:+1:

**Comment by jaroel** [comment]
What needs to be done, and who is going to do this?

**Comment by jensens** [comment]
If I can choose between minor performance impact at import time vs. not hiding circular imports et al: 
I take the latter. Lets keep it using ``pkg_resources.DistributionNotFound``.

**Comment by jaroel** [comment]
+

**Comment by zupo** [comment]
I support @jensens view.

**Comment by thet** [comment]
Some more arguments regarding this discussion:

While @do3cc proposal to use pkg_resources also has the advantage to be able to check for package version conflicts, which can come quite handy in some cases, it has the disadvantage to not beeing able to check for the existence of a specific identifier from a module. 

For example, if I want to check for the existence of ``IDisableCSRFProtection`` from ``plone.protect.interfaces`` which was added in plone.protect 3.0, it's easy with catching ``ImportError``:

```
try:
    # Soft dependency to make this package work without plone.protect
    from plone.protect.interfaces import IDisableCSRFProtection
except ImportError:
    IDisableCSRFProtection = None
```

With ``pkg_resources`` I have to check for the existence of the distribution and the version, where this interface was added and still have no guarantee, that it exists (e.g. if it will be removed in version 4.0):

```
try:
    pkg_resources.get_distribution('plone.protect>=3.0')
except (pkg_resources.DistributionNotFound, pkg_resources.VersionConflict):
    IDisableCSRFProtection = None
else:
    # Soft dependency to make this package work without plone.protect
    from plone.protect.interfaces import IDisableCSRFProtection
```

However, I also don't want to debug masked circular import errors... Plone is predestinated to have circular imports, but I rarely come across such errors.

**Comment by do3cc** [comment]
I came across circular imports. It is terrible the first time it happens, because you might start questioning your sanity.
you can check for minimum and maximum requirements in get_distribution:
pkg_resources.get_distribution('plone.protect>=3.0,<4.0')

If your example was just an example and you don't actually know if IDisableCSRFProtection does get removed, please be aware that the ImportError check prevents you from getting notified that something you expect has changed.
Maybe the import location just has changed. By getting and not catching the import error, you give the developer the chance to analyse what the proper solution is. It might be much better than just not doing some action if there was an import error

**Comment by jensens** [comment]
I also debugged strange side effects from hidden ImportErrors and can confirm the pain. I'd also say beginners have no chance to get what happens.

Writing one time sane code and even if it costs some millis at startup is it worth compare to hours of insane debugging.

**Comment by thet** [comment]
``pkg_resources.get_distribution('plone.protect>=3.0,<4.0')`` is not the solution, because we want CSRF protection to work in future Plone versions also.
But if done with the pkg_resources check and the application fails with an ImportError in Plone 6, it's ok because this is an explicit hint that something has to be fixed.

**Comment by thet** [comment]
I'll go and update my editor snippets with the pkg_resources check, see how this will work out and keep this issue closed.

**Comment by gforcada** [comment]
@thet but then on your example I would first check if plone.protect exists and then if exists do a regular try/except ImportError for the import, this way you do not have to hardcode version numbers on the source code

**Comment by hvelarde** [comment]
+1 on @gforcada

**Comment by do3cc** [comment]
@gforcada What is wrong with specific version checks in code? This is not pinning to certain, currently but later outdated versions, but forbiding versions, known to not work with the code

**Comment by gforcada** [comment]
@do3cc nothing wrong in general, but given the specifics @thet described I would do it as a two step check, first if we have the distro, then if the specific thing I'm looking for.

As long as plone.protect 4.0 is not out of the door and thus you can not know if the import will still be there, you can make your code work now and forever with the approach that I described, with only version checks you can only force that versions.

So in general and for already released code that's totally fine and I would use and recommend, but for future deprecations, the approach that I suggested feels more robust to me.

**Comment by do3cc** [comment]
Ah, I got it now. My suggestion for to limit to version <4.0 was only an example, because I interpreted
@thet 
```
With pkg_resources I have to check for the existence of the distribution and the version, where this interface was added and still have no guarantee, that it exists (e.g. if it will be removed in version 4.0):
```
as if he thought, one can only define one version requirement

**Comment by thet** [comment]
@gforcada I think this would not solve the problem @do3cc suggestion tries to solve. Masking circular imports are still possible, when adding another try/except in the else clause like following, no?

```
# Soft dependency to make this package work without plone.protect
try:
    pkg_resources.get_distribution('plone.protect>=3.0')
except (pkg_resources.DistributionNotFound, pkg_resources.VersionConflict):
    IDisableCSRFProtection = None
else:
    try:
        from plone.protect.interfaces import IDisableCSRFProtection
    except ImportError:
        IDisableCSRFProtection = None
```
