### ISSUE TITLE
style guide: __version__ support?

### ISSUE THREAD

**Issue by gforcada** [plone/plone.api#218]
See the discussion here: https://github.com/plone/Products.CMFPlone/commit/1b0f9cfe8947cb67bc4fd11760a653c3113e4b33

Do we want to encourage that on all packages as a best practice?

**Comment by jensens** [comment]
+1

**Comment by jaroel** [comment]
-1
- People expect the version in setup.py.
- pkg_resource is a good enough api, when you need to know this programmatically. ie the version of the project, not the module.
- existing tooling cannot use __version__ in a module without additional configuration.

**Comment by jensens** [comment]
@jaroel i think you did not get the point:

the idea is to still declare the version in setup.py - but expose it as a variable in ``__init__.py`` like so::

    __version__ = pkg_resources.require("Products.CMFPlone")[0].version

as you can see in the above. this is pure convenience.

**Comment by jaroel** [comment]
It does mean that when you import the module, pkg_resources.require is called. Which has the same implications as #217

**Comment by adamcheasley** [comment]
@jaroel from my understanding of #217, `pkg_resources.DistributionNotFound` has been shown to be slower than `ImportError`. It didn't seem to be implying that we cannot use `pkg_resources.require`.

**Comment by jaroel** [comment]
As in, it is an performance hit. It still is a function call + some lookup.

**Comment by jaroel** [comment]
So, when you want to know the version of a package, you need to do two things:
1. Check if the package supports the \__version__ alias
2. Use this code:
```
import Products.CMFPlone
Products.CMFPlone.__version__
```

Or, what works for everything:
```
import pkg_resources
pkg_resources.get_distribution("Products.CMFPlone").version
```

**Comment by jaroel** [comment]
This better be a really nice bikeshed. ;)

**Comment by jensens** [comment]
ack :)

**Comment by jaroel** [comment]
;)

**Comment by jensens** [comment]
and there is even a pep around this http://legacy.python.org/dev/peps/pep-0396/
