### ISSUE TITLE
any editor support for zca xml style?

### ISSUE THREAD

**Issue by jensens** [plone/plone.api#219]
While going through code out in the wild, zcml is formatted in many different flavors. Now I looked for editor support, such as a plugin for $favorite editor.

Well, there is nothing. Bummer. Ok, looking at other editors, python and/or command line tools. 
Also nothing which can be configured to output it the ZCA way. What tool did I miss?

The only tool I found is ``xml_pp`` contained in http://xmltwig.org/ with  option ``-s indent_a`` option. Given the example 1 from http://docs.zope.org/zopetoolkit/codingstyle/zcml-style.html the results are as shown in the gist here https://gist.github.com/jensens/1e9c924b4a15cef18ea9

In my opinion the xml_pp output is much better readable than the ZCA style guide one.

Anyway, conclusion is, bad editor support of style guide recommendations results in bad style in zcml/xml in core and addon code.

**Comment by gforcada** [comment]
At the end ZCML is just XML so we need to set some rules/styleguide (xslt to the rescue?) and we can turn that into both a styleguide recommendation here at plone.api documentation and some checks and formatters on plone.recipe.codeanalysis...

I do like the xml_pp output a lot, it has the two main features I like:
- one attribute per line
- clear indentation
- *could we add it as a bonus to sort always attributes alphabetically?*

Last point, totally a pet peeve, would help a lot when refactorings are going on to easily spot things.

It also accounts for not creating crazy long lines which is also a big +1 when diff'ing changes, specially in a git three-way comparisons...

I see that this xmltwig is a Perl script, most probably it shouldn't be that hard to do it on python itself right? That would be great as a setuptools entry point for plone.recipe.codeanalysis to format all ZCML files according to this script...

**Comment by jensens** [comment]
It looks like it sorts the attributes. And yes, is a Perl script. Its for sure possible to port it. But don't underestimate the effort. I'd just use it as is, like we do with the js/css linters in code analysis.

**Comment by hvelarde** [comment]
AFAIK, Perl is a write-only language ;-)

**Comment by jensens** [comment]
I integrated the xml_pp tool in sublime. Gist and instructions here:
https://gist.github.com/jensens/4fc631616f5ef9ac4c6b

@hvelarde sure it is. But as long as I'am not the person in need to look at Perl code this is complety fine ;)

**Comment by frisi** [comment]
-1 for sorting attributes alphabetically.

when registering a browser page for example, i'm more interested in which interface it's available for and how it is named.

```
<browser:page
    name="my-cool-view"
    for="Products.CMFPlone.interfaces.siteroot.IPloneSiteRoot"
    template="cool-view.pt"
    class=".cool.Viewclass"
    permission="cmf.ModifyPortalContent"
    layer=".interfaces.MyTheme"
    />
```

instead of:

```
<browser:page
    class=".cool.Viewclass"
    for="Products.CMFPlone.interfaces.siteroot.IPloneSiteRoot"
    layer=".interfaces.MyTheme"
    name="my-cool-view"
    permission="cmf.ModifyPortalContent"
    template="cool-view.pt"
    />
```

maybe that's just a matter of how people are used to do things...

when it comes to sorting attributes in css and jsregistry.xml (i know - that's not zcml and only relevant for plone < 5 - just in case somebody wants to order attributes there too) i'd say it's even more important to keep the id first (not cacheable, compression etc) for better readability.

**Comment by jcbrand** [comment]
The nice thing about sorting is that it reduces cognitive load when writing the directive. You don't have to try and remember the correct order or even look it up somewhere, you just make sure that attributes appear alphabetically.

When looking things up, it's pretty trivial to do "find" in your editor and search by "name=", then you'll get the names of all browser views highlighted in the file.

**Comment by jensens** [comment]
+1 for alphabetically. The problem with "more interested in first" is that everybody is interested in different things and so you'll find many different orders. so fullack to @jcbrand

**Comment by adamcheasley** [comment]
+1 for alphabetically. As @jcbrand says, if we try to order them by some arbitrary measure of importance, you will spend the first few weeks having to go back and look up the correct ordering.

**Comment by frisi** [comment]
i don't have a strong opinion on that.

i just think that it's not necessary to enforce attribute-sorting as suggested by @gforcada.

neither i wanted to say that everybody should follow the same order. @jcbrand: find also works for arbitrary sorted attributes.
in addition, figuring out the alphabetical order of attributes increases cognitive load (at lease for me personally ;-)

my point simply is: agree on an easily readable style for xml files in general (not just zcml), but don't add extra workload for people.

if we sort attributes, the next step is to sort directives too: `adapter, browser:page, browser:viewlet include` or - depending which namespaces you prefixed: `include page, viewlet, zope:adapter`
(as the order can be important here (includes!), (automatic) sorting might not be a good idea here anyway.

**Comment by gforcada** [comment]
@frisi maybe I was a bit too strong on that, I just wanted to highlight that just like sorting imports is pointless, the same should be for attributes, there's no difference where they are, so get a quick way to not have to stress yourself on deciding the order, but instead just relax and let your tooling do it, or as you just copy and paste things you don't have to worry about their order anymore at all.

Fair point on *not* sorting directives although, there a lot of valid points (keep things together, incremental update... etc etc) to not advise on any sorting.

Maybe the advice here would be actually to split any zcml file with more than X amount of directives, so that if you happen to have lots of ``browser:viewlet`` and ``browser:page`` on the same folder, put them either on different zcml files (``browser.zcml`` and ``viewlets.zcml``) so things are a bit more tidy up.

Still, not to be used everywhere always, but only where it make sense (TM).

**Comment by jcbrand** [comment]
> in addition, figuring out the alphabetical order of attributes increases cognitive load (at lease for me personally ;-)

@frisi If you're doing it manually, you're doing it wrong. You should be using your editor to do the sorting.

**Comment by jcbrand** [comment]
That said, it's ok with me if we don't force any particular order. My point was more that IF we force an order, alphabetic order makes the most sense to me.

**Comment by davisagli** [comment]
-1 for do

David Glick
(mobile)

**Comment by davisagli** [comment]
-1 for forcing an order

**Comment by jaroel** [comment]
No way on sorting attributes.

**Comment by jaroel** [comment]
What needs to be done, and who is going to do this?

**Comment by jensens** [comment]
label is "question" - by intend - so this was a question. there are answers and opinions in here. So "What needs to be done, and who is going to do this?" makes not that much sense.

**Comment by idgserpro** [comment]
Well, @ale-rt implemented something about zcml in https://pypi.org/project/zpretty/, but I'm not so sure of it's adherence to zcml style guide in some situations, for example in [one line empty tags](https://zopetoolkit.readthedocs.io/en/latest/codingstyle/zcml-style.html#empty-tags). From a `plonecli` template:

```xml
  <!-- Set overrides folder for Just-a-Bunch-Of-Templates product -->
  <include package="z3c.jbot" file="meta.zcml" />
```

Running zpretty gives:

```xml
  <!-- Set overrides folder for Just-a-Bunch-Of-Templates product -->
  <include
      package="z3c.jbot"
      file="meta.zcml"
      />

```

**Comment by jensens** [comment]
FTR only: I usually use `xml_pp -i -s indented_a configure.zcml` which produces almost an output that is AFAIK compatible to what some styleguide for ZCML recommends (I found years ago in Zopeverse, nowadys at https://zopetoolkit.readthedocs.io/en/latest/codingstyle/zcml-style.html#style-guide). 

I have this as an alias `alias xmlpp='xml_pp -i -s indented_a'` since several years in my `.bashrc` and use it in my projects internally. 
`xml_pp` can be installed with `apt install xml-twig-tools`.

**Comment by ale-rt** [comment]
zpretty should be compliant with the ZCML style guide, if not it is a bug.
It has also some dumb sorting algorithm for attributes but I gave up implementing something smarter.
Ah! And it needs to be ported to Py3.
I will probably do that.
