### ISSUE TITLE
Differences by using catalog or api.content.find (at least with icons)

### ISSUE THREAD

**Issue by keul** [plone/plone.api#220]
Don't know if this is a know behavior and this is probably related to #214, but right now using...

    results = api.content.find(...)

returns a `ContentListing` collection, while using catalog...

    catalog = api.portal.get_tool(name='portal_catalog')
    results = catalog(...)

Returns lazymap items. The issue here is related to generating icons from search results.
Calling `plone_view.getIcon(results[0])` will fail using `api.content.find`.

**Comment by hvelarde** [comment]
for me this is a bug; the problem is the implementation is indeed [returning ContentListing](https://github.com/plone/plone.api/blob/master/src/plone/api/content.py#L565).

**Comment by adamcheasley** [comment]
I agree. I would expect api.content.find to return a lazymap. It would be a simple fix, but we'd want to make sure we wouldn't be losing some functionality by not returning a ContentListing.

**Comment by jaroel** [comment]
Or define an adapter for IContentListing to IContenIcon :)

**Comment by keul** [comment]
@jaroel :+1:

**Comment by hvelarde** [comment]
please do not start adding layer of complexity here; I think we need to clarify what are the differences between a list brains and a content listing collection; I though the original idea of having this method was to replace the direct call to the ``portal_catalog``. if that's the case then the implementation should return brains.

**Comment by jaroel** [comment]
Or use result[0].getIcon()

**Comment by jaroel** [comment]
Resolved, see #237
