### ISSUE TITLE
Remove doctests from docstings

### ISSUE THREAD

**Issue by hvelarde** [plone/plone.api#221]
IMO doctests just clutter docstrings and they don't provide neither good documentation, nor good tests.

I just saw that [api.content.find](https://github.com/plone/plone.api/blob/master/src/plone/api/content.py#L479) includes some doctests and I would prefer to remove them from there.

AFAIK, that's the only method implementing doctests in the whole package and I think they were not there when I first reviewed the code.

**Comment by adamcheasley** [comment]
+1

I actually raised this when the pull request came in, but it was said that the doctests provide further functional documentation. As this is the only function with a doctest, I agree with removing it.

**Comment by zupo** [comment]
Doctests have their place in this world. And the api.content.find is a very good example of how/when they should be used: not as tests, but as testable documentation. 

I'm -1 for removing. Moreover, I'm +1 for adding such examples to other methods.

**Comment by hvelarde** [comment]
:-1: for adding doctests to code; we already have tests for code on one side and narrative documentation with tests on the other; adding doctests will be completely useless, IMO:

* http://nedbatchelder.com/blog/200811/things_i_dont_like_about_doctest.html
* http://bemusement.org/narrative-tests
* http://bemusement.org/doctests-arent-code

**Comment by adamcheasley** [comment]
I agree with @hvelarde. Adding further doctests would just be noise as far as I'm concerned.

**Comment by jaroel** [comment]
They aren't tests, but code examples.
If they were tests, I'd actually have to check the output, right? ;)

**Comment by jaroel** [comment]
They are examples on how to call this function that show when you use function.func_doc.
