### ISSUE TITLE
allow plone.api in restricted python scripts?

### ISSUE THREAD

**Issue by frisi** [plone/plone.api#222]
just stumbled upon [a question on stackoverflow](http://stackoverflow.com/q/29201305/810427) today where a user wants to use plone.api to get the portal_catalog tool in a python script.

which lead me to start a short discussion whether we should care about usecases like this (and allow all api methods (or a subset) in restricted python) or just discourage the use of python scripts (and add documentation that plone.api won't work there and people should use browser views instead)

**Comment by jaroel** [comment]
We haven't done a security check, so plone.api might import modules that allow you to escape the RPython sandbox. 

Write a browserview that returns plone.api for now :)

If you still think this is a good idea, please re-open the ticket and make sure the security check gets done ;)
