### ISSUE TITLE
Provide a machine readable list of old-new usages

### ISSUE THREAD

**Issue by gforcada** [plone/plone.api#225]
In plone.app.mosaic @datakurre wondered if plone.recipe.codeanalysis was providing some linter to check if old-ways of doing things could be replaced by plone.api calls. It doesn't (https://github.com/plone/plone.recipe.codeanalysis/issues/118).

There @saily suggested that instead of hard-coding them on p.r.codeanalysis, it could fetch some XML/JSON/CSV from plone.api itself where it was described what was the old approach (i.e. ``getToolByName`` vs ``plone.api.portal.get_tool``.

Thus, this ticket is born. Please discuss :)

**Comment by jaroel** [comment]
I'd suggest to build a static linter first. If we have loads of changes all the time, we'll make it dynamic :)
Sounds good enough?

**Comment by gforcada** [comment]
Good enough: https://pypi.python.org/pypi/flake8-plone-api consider it totally **alpha** I just made up the replacements by looking at which (weird) methods where being used on the implementation of each plone.api method.

Suggestions and pull requests welcome.

**Comment by jaroel** [comment]
A quick test run on some client code shows it works like a charm!
Awesome!
