### ISSUE TITLE
send_email need to be updated to work with Plone 5.0b2

### ISSUE THREAD

**Issue by pbauer** [plone/plone.api#226]
since mail-setting are stored in the registry from 5.0b2 plone.api needs to look there instead of doing stuff like ``portal.getProperty('email_from_address', '')``. The sensible thing to do would be check for email-settings in the registry and have a fallback to portal-properties, right?

**Comment by hvelarde** [comment]
:+1:

**Comment by jensens** [comment]
+1 and I also think a fallback to the old place is a good idea.

**Comment by gforcada** [comment]
Let's add a deprecation notice though.

So we can grep for them later on and remove the fallback code at some point, and not keep them forever :)

@jensens I remember reading a FWT notes and some mails from you about deprecation warnings, was there any consensus/docs about it on how to proceed?

**Comment by pbauer** [comment]
Fixed in #226. Sorry I did not link the pr to this ticket.

**Comment by jensens** [comment]
ok, i think i need to prioritize this task higher to get it done!

! OT

For this kind of in-code problems python warnings are the right thing::

    import warnings
    def foo(bar):
        baz = newandhip.get(bar, None)
        if baz is None:
             warnings.warn("fetch from old and busted, use new and hip!", DeprecationWarning)
             baz = oldandbusted.get(bar, None)

see also the python documentation: https://docs.python.org/2/library/warnings.html
this is the right thing to do in code. 

How to make this things shown up is a different topic, but after merge of https://github.com/zopefoundation/Zope/commit/cbb81d741c4587360d23f4e0a89a5b0a845f075c the buildout/recipe setting ``deprecation-warnings`` will have a chance to work again.

The topic "Deprecation Done Right"  misore complex than it initially seems to be.
