### ISSUE TITLE
send_email does not work with PrintingMailHost w/o MailHost configured

### ISSUE THREAD

**Issue by jensens** [plone/plone.api#228]
In development scenarios Products.PrintingMailHost helps a lot. 
But ``send_email`` does not work with it unless a Mailhost is configured in the registry. In dev, when one trashes all the time the database this is annoying.

The configuration check is great, but we may want to disable it if Plone is in debug-mode?

**Comment by zupo** [comment]
+1

**Comment by gforcada** [comment]
:+1: maybe checking specifically for P.PrintingMailHost being around would be cleaner? I can imagine someone trying to send real emails from a debug instance (maybe crazy, but worse things can be seen on the wild...)

**Comment by jensens** [comment]
+1 @gforcada - good point

**Comment by jaroel** [comment]
What needs to be done, and who is going to do this?

**Comment by jensens** [comment]
@jaroel I'd say @gforcada for checking specifically for ``Products.PrintingMailHost`` and when there disabling the check is the task. An easy task. I can do this but have no time in next future to do so. Any volunteers welcome!

**Comment by jaroel** [comment]
I have no idea on how I can test this without un-patching and patching the PrintingMailHost patches.

**Comment by jaroel** [comment]
This is resolved in #244
