### ISSUE TITLE
Write a method that shows the list of tabs or selected tab of plone admin interface?

### ISSUE THREAD

**Issue by rodfersou** [plone/plone.api#232]
I was studding [this code](https://github.com/plone/plone.app.layout/blob/master/plone/app/layout/viewlets/common.py#L305), and I think it is possible to change it into some methods that list all tabs available and the current tab.

![currenttab](https://cloud.githubusercontent.com/assets/131209/7681069/ed749474-fd42-11e4-9657-1502c8e7d99f.png)

What do you think? is it an interesting contribution to plone.api? If so, what names would I give to these methods?

**Comment by adamcheasley** [comment]
Personally, I don't think I've ever needed code to list the available tabs from the edit toolbar. I therefore don't think this falls under the remit of plone.api.

**Comment by jaroel** [comment]
Hi Rodrigo,

Thanks for your interest. The API for getting actions should be clean enough for now.
For example, see https://github.com/plone/plone.app.content/blob/master/plone/app/content/browser/reviewlist.py#L131 .

**Comment by rodfersou** [comment]
@jaroel and how can I get the current action?

**Comment by jaroel** [comment]
https://github.com/plone/plone.app.layout/blob/master/plone/app/layout/viewlets/common.py#L357

**Comment by rodfersou** [comment]
@jaroel I have a use case here that I have to load one JS resource just on view tab (doesn't matter if it is the default view or other one, just shoud not be the other tabs - edit / sharing / etc..)

If you read the code you saw, it is not that simple to know if you are into view tab..

**Comment by jaroel** [comment]
Please open a thread at https://community.plone.org/.

**Comment by djowett** [comment]
Try using Diazo....

<rules css:if-content="#edit-bar #contentview-view.selected">
      // load JS resource here
</rules>

Or, better, always load the JS resource through the JS registry
and use JQuery to selectively activate it:

if ($("#contentview-view.selected").length > 0){
     // activate JS resource

}


On 18/05/15 15:44, Rodrigo Ferreira de Souza wrote:
>
> @jaroel <https://github.com/jaroel> I have a use case here that I have 
> to load one JS resource just on view tab (doesn't matter if it is the 
> default view or other one, just shoud not be the other tabs - edit / 
> sharing / etc..)
>
> If you read the code you saw, it is not that simple to know if you are 
> into view tab..
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/plone/plone.api/issues/232#issuecomment-103083343>.
>

-- 
Daniel Jowett

*Jowett Enterprises Ltd*
Tel: 0333 3 553 773
Mobile: 07870 667 126
daniel@jowettenterprises.com
www.jowettenterprises.com

**Comment by rodfersou** [comment]
@djowett I toughs about it at first, but my requirement was to make this happen into server side, not client side.

Well.. in the truth I already did [one implementation](https://github.com/collective/collective.glossary/blob/master/src/collective/glossary/browser/views.py#L108) that works.. I went here just to see if someone else needs this check and if I can help with some code at plone.api.

**Comment by djowett** [comment]
Ah, fair enough to offer...
