### ISSUE TITLE
API not compatible with Plone 4.1

### ISSUE THREAD

**Issue by hvelarde** [plone/plone.api#237]
There are some tests failing: https://travis-ci.org/plone/plone.api/jobs/64567653

**Comment by adamcheasley** [comment]
Looks like we're trying to adapt a list to IContentListing. This might be a difference in how search results are returned in older versions of Plone? I'm just guessing at the moment, but I'll see if I can take a closer look at some point this week.

**Comment by hvelarde** [comment]
can anybody explain me what are the benefits of adapting the catalog results to ``IContentListing``?

I think the find method is a fantastic enhancement to the API, but it seems to me that using ``plone.app.contentlisting`` will break compatibility with Plone 4.0 also.

**Comment by adamcheasley** [comment]
I have to agree. I think this was discussed on another thread somewhere, but I personally don't see the benefit in adapting the results.
I'm +1 for removing this.

**Comment by zupo** [comment]
Shall we have api.content.find (returns brains)  AND api.content.list (returns IContentListing)?

**Comment by jaroel** [comment]
I'll remove the IContentListing adapter from master.

**Comment by hvelarde** [comment]
This was not completely fixed as you can see here: https://travis-ci.org/plone/plone.api/jobs/66190312
