### ISSUE TITLE
content.get_state() documentation error.

### ISSUE THREAD

**Issue by zopyx** [plone/plone.api#245]
Besides ValueError(no idea when this is raised) 

    plone.api.content.get_state() 

raises 

    <class 'Products.CMFCore.WorkflowCore.WorkflowException'>

in case when no workflow is associated with the content object (e.g. File or Image).

**Comment by jaroel** [comment]
Thanks, this bug report made obvious that get_state is leaky and incomplete.
I've filed a bug report for this: #246 .

I'll fix the docs for now.

**Comment by jaroel** [comment]
I don't think it actually raises a ValueError, so I'll replace that too.

**Comment by jaroel** [comment]
This is fixed by #247.
