### ISSUE TITLE
plone.api.content.get_state should handle objects without a workflow definition.

### ISSUE THREAD

**Issue by jaroel** [plone/plone.api#246]
Products.CMFCore.WorkflowCore.WorkflowException is raised when there is no workflow definition for the object.
This make the current abstraction leaky, ie the client code needs to handle the exception and we therefor cannot replace the underlying workflow engine.

The implementation should check that there really is no workflow is associated with the content object, instead of just catching the exception. WorkflowException is too generic for this. Catching it will mask other errors and prevents logging them.

We should handle this situation and return None instead to make the client code cleaner.
Here is an example for the client code:

The new approach gives us code that looks like:
```python
state = api.content.get_state(context=my_image)
if state is None:
    # Handle this somehow
else:
    print "state: ", state
```
or
```
state = api.content.get_state(context=my_image)
print "state: ", state if state else 'Unknown'
```

Where in the old situation client code looks like:
Handle the exception
```python
from Products.CMFCore.WorkflowCore import WorkflowException

try:
    state = api.content.get_state(context=my_image)
except WorkflowException:  # this swallows all other WorkflowExceptions too.
   # Handle this somehow
else:
    print "state: ", state
```

**Comment by jaroel** [comment]
Passing in a default value doesn't affect existing code, but allows cleaner new code:
```python
plone.api.content.get_state(context=my_image, default=None)
>>> None
plone.api.content.get_state(context=my_image, default='Unknown')
>>> 'Unknown'
plone.api.content.get_state(context=my_image)
>>>  <some exception>
```

**Comment by jaroel** [comment]
Does this look sane?

**Comment by adamcheasley** [comment]
Looks sane to me!
