### ISSUE TITLE
content.create should notify creation events

### ISSUE THREAD

**Issue by tomgross** [plone/plone.api#258]
content.create should notify IObjectAddedEvent and / or  IObjectCreatedEvent 
maybe other DX / AT creation / adding events?

this is useful for triggering indexing for example.

**Comment by adamcheasley** [comment]
Yes I think you're right. It looks like calling processForm will notify ObjectInitializedEvent, but from what I can see, IObjectAddedEvent is not notified anywhere.

**Comment by mattss** [comment]
As far as I know, IObjectAddedEvent and IObjectCreatedEvent are pretty low-level events that are fired by zope under the hood. We use plone.api a *lot* now and would have hit serious issues if these events were not fired when using it. @tomgross Do you have any example code or tests to show this isn't happening?

**Comment by adamcheasley** [comment]
It appears that the OFS ObjectManager notifies these events. I'm assuming this would happen for both DX and AT types created with plone.api.

**Comment by tomgross** [comment]
According to collective.indexing.subscribers.zcml should be indexed on IObjectCreatedEvent, which was not the case when using plone.api.content.create for DX content (processForm is an AT thingy)

**Comment by adamcheasley** [comment]
It appears that OFS does not notify the IObjectCreatedEvent. It looks like these are fired by Products/CMFCore/TypesTool.py in the `FactoryTypeInformation` class. Now I thought this class was used by DX too, but maybe I'm wrong.

**Comment by mattss** [comment]
@tomgross if you are using collective.indexing then you won't get reindex events until the transaction boundary. Is that what you are seeing?

**Comment by tomgross** [comment]
This works. The problem is somewhere else.
