### ISSUE TITLE
`plone.api.content.transition` does not reindex new state and permissions

### ISSUE THREAD

**Issue by davisagli** [plone/plone.api#265]
`plone.api.content.transition` does not reindex allowedRolesAndUsers or review_state, so it leaves the catalog inconsistent with the new state.

At the least we should mention this in documentation. Possibly we should make `transition` call reindexObject(idxs=['allowedRolesAndUsers', 'review_state']), though we might want a way to opt out of that in case it's called from code that is also making other changes that need to be indexed.

**Comment by adamcheasley** [comment]
Good spot!

**Comment by adamcheasley** [comment]
I dug into this a little further. `plone.api.content.transition` mostly uses `doActionFor` on the workflow tool. This in turn calls `_reindexWorkflowVariables` which appears to reindex the indexes above and also calls `reindexObjectSecurity`.
