### ISSUE TITLE
Allow [sg]et_registry_record to get an optional interface

### ISSUE THREAD

**Issue by gforcada** [plone/plone.api#269]
I add my records to the registry via a Interface, then to retrieve them back I use:

```
registry = getUtility(IRegistry)
records = registry.forInterface(IMyInterface)
records.my_register_record = 'something'
```

It would be great if plone.api allows me to do the same:

```
get_registry_record('my_register_record', interface=IMyInterface)
```

Sounds good/desirable? Wording of course up to debate :-)

**Comment by hvelarde** [comment]
+1 awesome!

**Comment by pcdummy** [comment]
+1, its very nice to expose registry settings on a view.
