### ISSUE TITLE
api.portal.get() should work in test layer setup

### ISSUE THREAD

**Issue by saily** [plone/plone.api#280]
i expected same behaviour as `plone.app.testing.helpers.ploneSite()` - at least as a fallback for `plone.api.portal.get()`.

**Comment by saily** [comment]
Ok, after some debugging we found out this is not possible in Layers.

**Comment by do3cc** [comment]
Some context for whoever stumbles over this too.
There is no guarantee that a Zope Server has only a single Portal.
While I did not verify this, I guess that during traversal the portal in the current context gets stored in such a way the portal.get() works.
In a test setup one, is outside of any portal. The helpers.ploneSite() context sets up an environment in which one IS in the context of a specific portal. As a nice side effect, he also provides the portal object.
