### ISSUE TITLE
Travis Test for 5.0 runs agains egg?

### ISSUE THREAD

**Issue by jensens** [plone/plone.api#281]
looking at https://travis-ci.org/plone/plone.api/jobs/82881168 there is plone.api is tested against the egg, not the source clone:
``/home/travis/build/plone/plone.api/eggs/plone.api-1.4.7-py2.7.egg/plone/api/tests/test_portal.py``
and therefore the test is red there.

**Comment by mauritsvanrees** [comment]
Let's see if commit 1fb751b6ce684c8fa48bc2a5b0fc0ac529aaa803 fixes it, which removes plone.api from the versions on Plone 5.

**Comment by mauritsvanrees** [comment]
That does the trick.
