### ISSUE TITLE
portal.send_email does not respect transaction aborts

### ISSUE THREAD

**Issue by jaroel** [plone/plone.api#283]
plone.api.portal.send_email uses immediate=True. This means that the email is sent multiple times if a ConflictError occurs.
Unless explicitly specified, email should be send at transaction boundary and/or using a mail queue.

https://github.com/plone/plone.api/blob/master/src/plone/api/portal.py#L177
http://docs.plone.org/develop/plone/misc/email.html

**Comment by gforcada** [comment]
:+1:

**Comment by jensens** [comment]
+1000

**Comment by agitator** [comment]
had exactly this problem with a client, reminder mails being sent out 7 times after transaction abort by plone.protect

btw. does someone know why 7 times?
