### ISSUE TITLE
RFC: add api call to get current negotiated language

### ISSUE THREAD

**Issue by jensens** [plone/plone.api#291]
At the moment its kind of difficult to get the current language. 
I mean the language actual negotiated.
At least I need this frequent.
http://docs.plone.org/develop/plone/i18n/language.html#getting-the-current-language
 
I propose to support ``plone.api.portal.get_language``.

**Comment by rnixx** [comment]
sounds reasonable

**Comment by thet** [comment]
+1

**Comment by jensens** [comment]
maybe also useful more widely in this context:
- ``plone.api.portal.get_configured_languages`` - languages configured in this portal
- ``plone.api.portal.get_default_language`` - language set as default in this portal.

So we should call my initial suggestion: ``plone.api.portal.get_current_language``.

**Comment by gforcada** [comment]
*not saying is a bad idea*

@jensens aren't these two last additions you mentioned only one portal.registry key away (in Plone 5 at least)?

**Comment by jensens** [comment]
@gforcada oh, sure, in plone5 it is in registry. Also there are vocabularies. Well, at the moment I'am struggeling with 4.3 sites :) - so we do not need them. but ``plone.api.portal.get_current_language`` is still a thing.

**Comment by gforcada** [comment]
@jensens sure, I was not against implementing them, just saying that it would be really easy to do so :-)

**Comment by ebrehault** [comment]
Don't you think it could also be useful to have an API method to translate?
Something like `plone.api.portal.translate(msgid, domain='plone', lang=None)` (and if lang is None we use current negociated lang)

**Comment by gforcada** [comment]
@ebrehault :+1:

**Comment by hvelarde** [comment]
+1 also on @ebrehault

**Comment by gforcada** [comment]
@jensens with @ebrehault #302 and #304 this could be closed, right? Reopen if not.
