### ISSUE TITLE
Close plone.api conventions style guide

### ISSUE THREAD

**Issue by thet** [plone/plone.api#294]
The plone.api styleguide was finally copied over and integrated in http://docs.plone.org/develop/styleguide/index.html ( https://github.com/plone/documentation/tree/5.0/develop/styleguide ) and also enhanced with other style guide information, especially for JavaScript.
To avoid to have two places which can get out of sync, I'd propose to close/remove the conventions in this repository: https://github.com/plone/plone.api/blob/master/docs/contribute/conventions.rst

**Comment by jensens** [comment]
+1 for less redundancy

**Comment by gforcada** [comment]
+1!

**Comment by hvelarde** [comment]
+1
