### ISSUE TITLE
API should show deprecation warnings to help migrate code

### ISSUE THREAD

**Issue by hvelarde** [plone/plone.api#297]
Plone 5 removed various tools without deprecation warnings on Plone 4; seems to me an easy way to help fix that is by adding such deprecation warnings inside plone.api.

For instance, any code asking for the [Calendar Tool](https://github.com/plone/Products.CMFPlone/issues/1320) should show a warning:

``` python
calendar_tool = api.portal.get_tool('portal_calendar')
```

This enhancement will help accelerating the adoption of plone.api and simplifying Plone internals by having a centralized place to put all of this messages.

**Comment by gforcada** [comment]
For this specific use case (tools deprecation) it looks like a valid use case, but as usual, the deprecation warning should be managed on every package IMHO.

@jensens was some time ago looking for a generic approach to handle that, so we can document and try to make sure deprecations and properly added.

I guess it will be part of the upcoming [Alpine City Sprint](http://www.coactivate.org/projects/alpinecitysprint-2016/project-home).

Maybe unrelated but I think that more than deprecation warnings on unrelated packages or the packages themselves we should use something like https://github.com/gforcada/flake8-deprecated/blob/master/flake8_deprecated.py (disclaimer I wrote it).

So a flake8 plugin that inspects your code and already gives you hints about what is already deprecated or will be in the future.

**Comment by gforcada** [comment]
Oh, I forgot: making a tool that checks if a deprecation warning should be added given certain changes (ie a commit) would be even more useful.

If a class is removed from ``interfaces.py``, probably that needs a deprecation warning, if a python module or package gets move around, the same applies.

So if jenkins could help on that it would be perfect.

/me starts dreaming on that tool :)

**Comment by hvelarde** [comment]
thanks, @gforcada, the Alpine City Sprint looks as a formidable event... good luck!

**Comment by jaroel** [comment]
I'm closing this issue, because a solution for this is out of scope for plone.api.
Please continue this in https://github.com/plone/Products.CMFPlone/issues/1320

Have a nice day, and thank you!
-Roel
