### ISSUE TITLE
Multiple test isolation problems

### ISSUE THREAD

**Issue by do3cc** [plone/plone.api#309]
Uncovered by a plone.testing version from an open PR:
https://github.com/plone/plone.testing/pull/19
results:
http://jenkins.plone.org/job/pull-request-5.0/902/console
related references:
https://github.com/plone/Products.CMFPlone/issues/447

**Comment by gforcada** [comment]
#310 should fix it, either that or we change the layer to a functional one

**Comment by gforcada** [comment]
Fixed on #310
