### ISSUE TITLE
api.content.move should warn if you are moving to the parent folder of the element

### ISSUE THREAD

**Issue by gforcada** [plone/plone.api#313]
So if **both** source and target are specified and the parent's source is already target, there's no need to move anything.

This still allows to not pass a target and make renaming happen.

Opinions?

**Comment by hvelarde** [comment]
skipping the operation should be enough, IMO.

**Comment by gforcada** [comment]
Fine with me as well

**Comment by mauritsvanrees** [comment]
Skipping seems fine. I had this recently where running an upgrade step for a second time would try to move an item to the folder where it already was. It worked fine, but was unnecessary.

**Comment by jaroel** [comment]
It is probably replacing the `if target:` check with something like `if target and target is not source.aq_parent`
