### ISSUE TITLE
portal.rst Code-Block is not right displayed, remove colon

### ISSUE THREAD

**Issue by 1letter** [plone/plone.api#315]
Please remove the last colon at the end of Line 230(in the Raw-File) in [portal.rst](https://github.com/plone/plone.api/edit/master/docs/portal.rst). As long as the double colon is in front of the code block, the block is not right displayed.

**Comment by gforcada** [comment]
Fixed in https://github.com/plone/plone.api/commit/a13257a6b7cea4808e77eaa03ad73e10221f0162 thanks for reporting!
