### ISSUE TITLE
Be nicer to non-Plone projects using plone.api

### ISSUE THREAD

**Issue by zupo** [plone/plone.api#316]
I use plone.api's utilities even in non-Plone projects. However in order to not import the entire Plone stack I have an internal release with a single commit that removes all imports from ``plone.api.__init__.py``. Would be nice to have this in upstream as an option.

```diff
src/plone/api/__init__.py
@@ -1,7 +1,2 @@
  # -*- coding: utf-8 -*-
  # flake8: noqa
 -from plone.api import content
 -from plone.api import user
 -from plone.api import group
 -from plone.api import portal
 -from plone.api import env
```

**Comment by adamcheasley** [comment]
I'm interested to know what type of non-Plone projects. Are these pure Zope sites?

**Comment by zupo** [comment]
Pyramid projects. Using mostly conventions and things in https://github.com/plone/plone.api/blob/master/src/plone/api/validation.py.

**Comment by gforcada** [comment]
@zupo wouldn't make more sense to create an external project for those validators?

**Comment by zupo** [comment]
And have one more package, for just a few lines of code? Maybe? But also, maybe not?

**Comment by jaroel** [comment]
I'd just copy `validation.py` into your project :)
If you depend on plone.api just for validation.py, you'll also get https://github.com/plone/plone.api/blob/master/setup.py#L33  ;)

**Comment by hvelarde** [comment]
he's the father of the creature; leave him alone!

![leave-britney-alone](https://cloud.githubusercontent.com/assets/341393/16050237/4826cd46-3231-11e6-9299-2dd39e9b41ae.png)

**Comment by zupo** [comment]
lol :D

**Comment by zupo** [comment]
Valid points, let's not do this.
