### ISSUE TITLE
Return a default value if no registry record is available

### ISSUE THREAD

**Issue by hvelarde** [plone/plone.api#317]
I have seen a common pattern arise in my code:

``` python
record = ISocialLikeSettings.__identifier__ + '.enabled_portal_types'
try:
    enabled_portal_types = api.portal.get_registry_record(record)
except InvalidParameterError:
    enabled_portal_types = []
```

can we have a default value instead?

``` python
record = ISocialLikeSettings.__identifier__ + '.enabled_portal_types'
enabled_portal_types = api.portal.get_registry_record(record, [])
```

**Comment by hvelarde** [comment]
see for instance this PR: https://github.com/collective/sc.social.like/pull/67/files

the pattern is repeated around 13 times.

**Comment by gforcada** [comment]
If you are installing the registry settings through an interface they are either all there or none, but I wouldn't try/except each call...

And then, if you are using an interface you can also do:

```
api.portal.get_registr_record(interface=IMySettings, name='field')
```

So you can skip the ``__identifier__ + '.field' `` code.

**Comment by hvelarde** [comment]
nice to know, but the default value could be useful anyway or I would need to test if the returned value is `None` in all places.

**Comment by gforcada** [comment]
Each registry key can provide a default value per se, I would only add the try/except if you are not sure that the registry key *is there at all*, if the value is one or another that's another matter which can be solved with a default value on the registry key.

**Comment by hvelarde** [comment]
if the record is somehow deleted then the code will rise `InvalidParameterError`; I want to avoid that kind of situations with this enhancement.

**Comment by idgserpro** [comment]
> if the record is somehow deleted then the code will rise InvalidParameterError;

Not only deleted: suppose you have a package, already installed, and from *now on* you decide to use a registry.xml in an upgradeStep for a specific feature.

If you have a browser view that asks for this new registry value and you didn't run your upgradeStep before rendering, you need the `try/except` as well or you get an error.

We're +1 for this approach from @hvelarde:

```python
enabled_portal_types = api.portal.get_registry_record(record, [])
```

This way, everyone who are still using `InvalidParameterError` will not break, but those who want to get rid of the `try/except` will benefit.

**Comment by hvelarde** [comment]
@idgserpro that's exactly the pattern we have been facing lately:

https://github.com/collective/collective.texttospeech/blob/master/src/collective/texttospeech/browser/__init__.py#L21-L27

**Comment by gforcada** [comment]
@hvelarde I'm waiting for your pull request :-)

**Comment by hvelarde** [comment]
@gforcada I have no idea on how to implement this; I think we need some marker class or something like that to avoid confusing , for instance, a default value of `None` with the default ignore value; can you point me to some code implementing that?

**Comment by jaroel** [comment]
Remember: using a default value will stop showing error pages, but will also prevent an error_log entry for actual users when the key should be there.

In the mean while:

    from plone.api.exc import InvalidParameterError

    _marker = []

    def get_record(interface, name, default=_marker):
        try:
            return api.portal.get_registry_record(interface=IMySettings, name='field')
        except InvalidParameterError:
            if default is not _marker:
                return default
            else:
                raise  # no default specified

    record = get_record(ISocialLikeSettings, enabled_portal_types, [])

**Comment by hvelarde** [comment]
this is mostly the use case we have, for instance, we don't want to display error when we are upgrading an add-on that has an upgrade step to add a new field on the registry.

BTW, I didn't implemented a solution just because [there's already a marker interface on the method](https://github.com/plone/plone.api/blob/master/src/plone/api/portal.py#L279) and I didn't want to add another.

**Comment by jaroel** [comment]
The supplied `get_record` is a utility function in your project, not something that already exists in plone.api.

Regarding the _marker variable, just declare another one outside the `get_registry_record` function, ie:

    _default_marker = []
    @required_parameters('name')
    def get_registry_record(name=None, interface=None, default=_default_marker):
    [...]
    if name not in registry:
        if default != _default_marker:
            return default
