### ISSUE TITLE
plone.api.content.copy fails if id is unchanged

### ISSUE THREAD

**Issue by djay** [plone/plone.api#340]
```plone.api.content.copy(foo.myid, bah, 'myid')```
will fail with

```  The id "myid" is invalid - it is already in use.```
Which is unexpected.
You have to omit the id param to make this work

**Comment by jaroel** [comment]
So, if you try to copy an object into the same folder using the same id, you'll get an exception?

**Comment by jaroel** [comment]
The offical method is to use safe_id=True, see https://docs.plone.org/develop/plone.api/docs/api/content.html#plone.api.content.copy

Having said that, the docs say .copy should raise InvalidParameterError, so that's a bug.
