### ISSUE TITLE
user.get_roles does not include local roles inherited from groups when using "inherit=False"

### ISSUE THREAD

**Issue by pbauer** [plone/plone.api#346]
As far as I know the `inherit=False` in `user.get_roles(user=foo, obj=bar, inherit=False)` is meant to ignore global roles. What it also does is ignore roles gotten from local roles of groups on the same object. That is inconsistent with `user.get_roles(user=foo, obj=bar, inherit=True)` which returns global and local roles owned by the user and local and gloabl roles inherited from groups the user is in.
The feature was added by @cillianderoiste in 654f749ff7a79eb7a21915b4a1b88f4870c51cd7.

**Comment by thet** [comment]
Fixed by #355
