### ISSUE TITLE
plone.api.user.has_permission does not check for AccessInactivePortalContent

### ISSUE THREAD

**Issue by thet** [plone/plone.api#356]
When checking a permission on an object with ``plone.api.user.has_permission``, the content object is not checked, if it is still active (already effective, not expired) and the user has the permission ``Products.CMFCore.permissions.AccessInactivePortalContent`` to access inactive content.

https://github.com/plone/plone.api/blob/master/src/plone/api/user.py#L311

I'm actually not sure, if that is the right place to do such a check. I just found a bug in a integration package, where we forgot to check for inactivity but did a check for a "View" permission.

Inactive content is still traversable, which I think is totally ok.
Maybe a conditional parameter to check for inactivity and accessibility would help.

**Comment by jaroel** [comment]
I don't think this would be a good idea, as the permission 'View' is granted and the object is publicly available (with standard workflows). I do get what you're saying, though.

We can add a flag to has_permission (ie check_inactive), but it can't be enabled by default without invalidating all existing code.
If we enable the check by default (like portal_catalog does), all code the assumes 'just check the View' permission is now broken :/
The flag makes no sense to me if it is disabled by default.

Maybe we can do `plone.api.user.can_view`?
```
def can_view(obj, username=None, user=None):
    if not has_permission('View', username=username, user=user, obj=obj):
        return False
    # check expiration dates
    # [...]
    return has_permission('AccessInactivePortalContent', username=username, user=user, obj=obj)
```

**Comment by thet** [comment]
Stale issue.
