### ISSUE TITLE
Update contribution docs

### ISSUE THREAD

**Issue by adamcheasley** [plone/plone.api#357]
Currently, the docs on how to contribute still reference the makefile, which no longer exists. These should be updated so that others can easily contribute. I believe the suggested way to get a dev environment these days is to use the coredev buildout, is that correct?

**Comment by gforcada** [comment]
If I want to hack on a single package without having *to care* about buildout.coredev complexity I usually check what's on ``.travis.yml`` those are usually the minimal steps that you need to get your project, at least tested :-)
