### ISSUE TITLE
api.content.move with id tries to rename when it doesn't need to

### ISSUE THREAD

**Issue by davisagli** [plone/plone.api#361]
`api.content.move` accepts an `id` parameter to rename the item that is being moved. It tries to do this even if the item already has that id, and in that case raises an exception. I think it would be better if it skips trying to rename in the case where the item already has the specified id.

**Comment by jaroel** [comment]
Docs say to use safe_id for that https://docs.plone.org/develop/plone.api/docs/api/content.html#plone.api.content.rename

Docs also say that rename should raise InvalidParameterError for safe_id=False, but it doesn't so that's a bug

**Comment by jaroel** [comment]
Nope, that's incorrect.
