### ISSUE TITLE
plone.api.user.has_permission lacks sanity check

### ISSUE THREAD

**Issue by jaroel** [plone/plone.api#372]
> (Pdb) from plone import api
> (Pdb) api.user.has_permission('kek')
> True
> (Pdb) api.user.has_permission('dadddadas')
> True

I would expect an exception as those permission do not exists. One could argue that False should be returned for all non-existing permissions, but I'd rather have an error because my code no longer is correct.

Any thoughts?

**Comment by adamcheasley** [comment]
Yes, that certainly confusing! I would go for an exception.

**Comment by adamcheasley** [comment]
Looks like at the moment this function is just a wrapper around a portal_membership method:
```        
return bool(portal_membership.checkPermission(permission, obj))
```

**Comment by jaroel** [comment]
Yep. Somewhere is a short circuit for a Manager to return True.
For normal users checkPermission does return False.
