### ISSUE TITLE
portal_transform api return error message instead of raising error when coverting pdf to plain text

### ISSUE THREAD

**Issue by nngu6036** [plone/plone.api#378]
```
try:
    transforms = getToolByName(context, 'portal_transforms')
    stream = transforms.convertTo(
            'text/plain',
            output_data,
            mimetype='application/pdf')
    if stream:
        text = stream.getData()
except:
    return ''

```
For some PDF, the return values is "Syntax Error: Expected the optional content group list, but wasn’t able to find it, or it isn’t an Array Permission Error: Copying of text from this document is not allowed.“,

**Comment by jaroel** [comment]
This issue was moved to plone/Products.PortalTransforms#21
