### ISSUE TITLE
Unexpected behavior in content.delete

### ISSUE THREAD

**Issue by rafaelbco** [plone/plone.api#383]
If I do:
```
api.content.delete(objects=[])
```
I expect that the function will do nothing and exit without errors. However, an exception is raised. 

The reason is the first line of code of the `delete` function:
```
objects = objects or [obj]
```
Since `objects` is an empty list and `obj` is `None` (the default value) we end up with `objects` being `[None]`.

An easy way to fix is to filter out `None` objects from the resulting list:
```
objects = objects or [obj]
objects = [o for o in objects if o is not None]
if not objects:
    return
```

**Comment by gforcada** [comment]
That could be handled on the decorators to keep the function simple and easy to read as well.
