### ISSUE TITLE
How do I create a Document with rich text/html using plone api ?

### ISSUE THREAD

**Issue by edemir206** [plone/plone.api#384]
Hi,

I'm using plone api to generate menus and pages dynamically, it works ok for folders and pages but i simply can't find a way to also add text/html to a page using the api.

The script I'm using to create is 

```
api.content.create(
        type='Document',
        title='Ementario',
        text='Documento do ementario do site '+r[0],
        container=curso)

```
But if I put the "text" argument it will raise an error on the page, in the docs i couldn't find anything about this.

**Comment by pbauer** [comment]
text is a instanc of RichTextValue, so you need to do `text=RichTextValue(u'foo', 'text/html', 'text/x-html-safe')`,

To access the value you can use `obj.text.raw` and `obj.text.output`. The later will pass the content through the safe-html transform.
