### ISSUE TITLE
Travis CI integration is broken

### ISSUE THREAD

**Issue by pbauer** [plone/plone.api#403]
Since plone.api is now part of the core does it make sense to have a travis-setup it in this package?

**Comment by hvelarde** [comment]
I think is easier to catch errors in Travis than having to wait for builds on Jenkins, but it's up to the testing team.

I can help fixing the builds, but on Thursday or Friday.

**Comment by hvelarde** [comment]
@loechel Travis is still broken and I don't understand the current setup; I need you help on this or I'll will have to completely remove the use of tox.

@gforcada can you help here?

**Comment by gforcada** [comment]
@hvelarde why has a testing related issue be a blocker? :thinking: one can still test pull requests with jenkins, so there is no blockage IMHO.

**Comment by gforcada** [comment]
as for the problem at hand, looking at the logs it feels like there is a missing pypi.org link missing in buildouts? :thinking:

**Comment by hvelarde** [comment]
@gforcada because we can't merge fixes or new features without testing; are plone.api tests running in Jenkins? where is the status?
