### ISSUE TITLE
IntIdMissingError: None

### ISSUE THREAD

**Issue by iham** [plone/plone.api#423]
plone 5.2a2
python 2.7

inside a test derived from PLONE_APP_CONTENTTYPES_FIXTURE
i get that error when
```python
api.content.copy(<content_obj>, self.portal, 'copied-item')
*** IntIdMissingError: None
```
any idea?

**Comment by iham** [comment]
Traceback (innermost last):
  Module ZServer.ZPublisher.Publish, line 144, in publish
  Module ZPublisher.mapply, line 85, in mapply
  Module Products.PDBDebugMode.runcall, line 68, in pdb_runcall
  Module ZServer.ZPublisher.Publish, line 44, in call_object
  Module plone.app.content.browser.actions, line 252, in __call__
  Module plone.app.content.browser.actions, line 315, in do_action
  Module plone.app.content.browser.actions, line 221, in do_redirect
IntIdMissingError: None

**Comment by iham** [comment]
the same happens in plone 5.2rc2

even using the ui actions copy & paste

**Comment by iham** [comment]
not part of plone.api - this is way deeper to search for.

https://github.com/plone/Products.CMFPlone/issues/2866

**Comment by gogobd** [comment]
`@@rebuild-relations` may help here, "Flush and rebuild IntIds" is what you want - of course you could destroy just every mosaic page with this but that's just the price one has to pay it seems.
