### ISSUE TITLE
Gracefully handle missing registry records on an interface

### ISSUE THREAD

**Issue by gforcada** [plone/plone.api#428]
Scenario:
- an existing interface with a few fields is initialized in the registry
- the code is deployed and GenericSetup takes care of creating the records and initializing them
- some time afterwards the interface gets updated with new fields
- as soon as the code is deployed and a code path calls ``plone.api.portal.get_registry_record(interface=XXX, name=YYY)`` it breaks because the new fields are still not registered

Fortunately, ``plone.registry`` allows to **not** check if there are missing values on an interface.

This way, it can gracefully handle the case that the code gets deployed but the upgrade steps/Generic Setup code still has not run.

As long as the new fields are not queried for, everything should be working fine as usual.

If not, the website would have to be put offline to avoid users getting errors, with this, the website would never have downtimes nor users would get errors :+1:

**Comment by mauritsvanrees** [comment]
PR merged. Thanks!
