### ISSUE TITLE
Travis tests for docs fail

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/plone.api#437]
See for example the results for [this PR](https://travis-ci.org/plone/plone.api/builds/650212023). The Plone tests pass, but the isort/flake8/docs tests fail. More precisely: the docs tests:

```
File "api/content.rst", line ?, in default
Failed example:
    find(context=context)
Exception raised:
    Traceback (most recent call last):
      File "/opt/python/2.7.15/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest default[0]>", line 1, in <module>
        find(context=context)
    NameError: name 'find' is not defined
```

It fails for [this line](https://github.com/plone/plone.api/blob/1.10.0/src/plone/api/content.py#L637) in an inline doctest in `content.py`. 

You would think that it would fail a [few lines earlier](https://github.com/plone/plone.api/blob/1.10.0/src/plone/api/content.py#L626), the first time that `find` is called. But that line does not trigger, because there is no white line before the line with `>>>`. 

Could be fixable by doing `from plone.api.content import find` (bit unofficial, but okay). But then it fails because there is no portal in this test.

We could try to setup the test better.
But really, I think the problem is that there is an inline doctest.  The `find` function is the only function that has this.
Note that `bin/test` does not run this inline test.

So: am I right in assuming that we do not want this inline doctest and should just remove it?

**Comment by ale-rt** [comment]
I totally agree.
I do not even know why that function is so different from the other ones.
