### ISSUE TITLE
IndexError when catching WrongType in set_registry_record

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/plone.api#464]
I call this code:

```
api.portal.set_registry_record(
        name="domains", value=[domain], interface=ICachePurgingSettings
    )
```

Looks fine at first glance but it contains an error. I am settings domains to a list here, but it must be a tuple. `plone.api` sees this and catches the `WrongType` exception and tries to turn this into an `InvalidParameterError`. But this gives a traceback:

```
Traceback (innermost last):
...
  Module plone.api.portal, line 2, in set_registry_record
  Module plone.api.validation, line 81, in wrapped
  Module plone.api.portal, line 379, in set_registry_record
IndexError: list index out of range
```

The index error is raised by [these lines](https://github.com/plone/plone.api/blob/1.10.2/src/plone/api/portal.py#L375-L379). These lines go through the fields of the interface, and strangely look for a field with name `field_one`. This seems an accidentally hardcoded name taken from the tests. The error has been there since 2015 (!) when `set_registry_record` got support for interfaces, in PR #286.

In the traceback it is in `plone.api` 1.10.2, but it is still there on master.

I will fix it.

**Comment by Thokas** [comment]
Duplicate of #435

**Comment by mauritsvanrees** [comment]
Ah, correct. I will close this one, and assign the other to me.
