### ISSUE TITLE
`plone.api.content.get(path)` returns a field if it finds one

### ISSUE THREAD

**Issue by sneridagh** [plone/plone.api#487]
Given a path like:

`path = '/de/examples/blocks`

and no content named blocks, it will get and return the `blocks` field content, because of `restrictedTraverse`...

Since `plone.api.content.get` promises to return a content type, we should not return anything that it's not.

**Comment by ericof** [comment]
@mauritsvanrees, @pbauer Considering the 2.0x branch only targets Python 3, I'm considering checking if the returned value is an instance of Dexterity, if it is not an instance, return None.
Any objections?

**Comment by ale-rt** [comment]
I see the issue, +1 on removing this "buggy feature".
What about checking if the object found provides the `Products.CMFCore.interfaces.IContentish` interface?
