### ISSUE TITLE
Update link to docs

### ISSUE THREAD

**Issue by stevepiercy** [plone/plone.api#491]
In the repo configuration settings, there is a link to the docs in the About section:

[docs.plone.org/develop/plone.api/docs/](http://docs.plone.org/develop/plone.api/docs/)

But in `README.md`, we now use:

https://6.dev-docs.plone.org/plone.api/

Please update the repo settings accordingly. Thank you!

Note, we need to remember to do this again, once the Plone 6 docs are final.

**Comment by rohnsha0** [comment]
but where is the file? that's to be changed?

**Comment by rohnsha0** [comment]
> In the repo configuration settings, there is a link to the docs in the About section:
> 
> [docs.plone.org/develop/plone.api/docs/](http://docs.plone.org/develop/plone.api/docs/)
> 
> But in `README.md`, we now use:
> 
> https://6.dev-docs.plone.org/plone.api/
> 
> Please update the repo settings accordingly. Thank you!
> 
> Note, we need to remember to do this again, once the Plone 6 docs are final.

but where is the file? that's to be changed? @stevepiercy

**Comment by stevepiercy** [comment]
It is not in a file. It is in the repo configuration settings, something that only privileged users have access to.

On https://github.com/plone/documentation, I see this:

![Screen Shot 2022-08-13 at 12 35 48 AM](https://user-images.githubusercontent.com/102112/184474154-386793bd-4736-4099-b512-b64bec1d07b5.png)

Clicking that gear icon brings up a dialog window.

![Screen Shot 2022-08-13 at 12 38 04 AM](https://user-images.githubusercontent.com/102112/184474178-31fa3750-b7d9-41a8-ab42-f0db9603b004.png)

**Comment by rohnsha0** [comment]
> It is not in a file. It is in the repo configuration settings, something that only privileged users have access to.
> 
> On https://github.com/plone/documentation, I see this:
> 
> ![Screen Shot 2022-08-13 at 12 35 48 AM](https://user-images.githubusercontent.com/102112/184474154-386793bd-4736-4099-b512-b64bec1d07b5.png)
> 
> Clicking that gear icon brings up a dialog window.
> 
> ![Screen Shot 2022-08-13 at 12 38 04 AM](https://user-images.githubusercontent.com/102112/184474178-31fa3750-b7d9-41a8-ab42-f0db9603b004.png)

Hahaha! Was Curious.... No Worries!

**Comment by rohnsha0** [comment]
Hahahahah! Was just curious...

**Comment by mauritsvanrees** [comment]
I have updated the link in the repo settings.
https://github.com/plone/plone.api

**Comment by stevepiercy** [comment]
Thank you!
