### ISSUE TITLE
Rename `master` branch to `main`

### ISSUE THREAD

**Issue by stevepiercy** [plone/plone.api#538]
After renaming the branch, update all documentation that references the `master` branch. This includes changes proposed in https://github.com/plone/plone.api/pull/544/files.

Additionally update the git submodule in Documentation.

This requires a repository administrator (anyone here want to take this on?) and coordination with the Documentation Team.

**Comment by MohammadBinAftab** [comment]
Hey Steve, has this issue been fixed? If not, can I work on it?

**Comment by stevepiercy** [comment]
@MohammadBinAftab no. I updated the issue description. In any case, please read and follow [First-time contributors](https://6.docs.plone.org/contributing/first-time.html), especially [Things not to do](https://6.docs.plone.org/contributing/first-time.html#things-not-to-do), [Contributing to `plone.api`](https://6.docs.plone.org/plone.api/contribute.html), and [Contributing to Plone](https://6.docs.plone.org/contributing/index.html).

@davisagli @mauritsvanrees @gforcada I assume any of you are qualified to rename the primary branch, and there are probably several other people, too. I can do the documentation bits. Are there any other bits, such as external workflows or Jenkins configuration?

**Comment by davisagli** [comment]
@stevepiercy I took care of the following:
- [x] Created main branch from master
- [x] Updated references to the master branch in the README and setup.py
- [x] Added a github ruleset to protect the main branch
- [x] Switched the repository's default branch to `main`
- [x] Updated the base of open PRs to target the `main` branch instead of `master`
- [x] Updated sources.cfg and mxsources.ini in buildout.coredev

I think that just leaves:
- [ ] Update the git submodule in the documentation repo (--> @stevepiercy)
- [ ] Remove the `master` branch

**Comment by davisagli** [comment]
^^ FYI @mauritsvanrees

**Comment by stevepiercy** [comment]
@davisagli how do we get `.editorconfig` to honor the settings we have for VSCode in Volto, Documentation, and Training?

## `.vscode/settings.json`

```json
{
  "[markdown]": {
    "editor.formatOnSave": false
  }
}
```

Both `plone.api` and `plone.restapi` have this situation. `.editorconfig` does not support this setting, yet it clobbers `.vscode/settings.json`. I also don't want to tweak something that uses `meta`, as I have no idea whether I would unintentionally break something.

**Comment by stevepiercy** [comment]
@davisagli I've updated the git submodule in documentation, and tested it to ensure it builds from scratch. Back to you.

**Comment by davisagli** [comment]
> .editorconfig does not support this setting, yet it clobbers .vscode/settings.json

@stevepiercy I don't follow. I tested and found that adding .vscode/settings.json as you showed is enough to prevent auto-formatting on save in VSCode, even if .editorconfig also exists.

**Comment by stevepiercy** [comment]
@davisagli OK, PyCharm greyed it out, which means it gets ignored. I don't have VSCode to test.

**Comment by davisagli** [comment]
@stevepiercy Matching the patterns in `.gitignore` is not the same as whether the settings are used by the editor.

**Comment by stevepiercy** [comment]
@davisagli OK, I see now. I didn't look in `.gitignore` before. I thought PyCharm was interpreting `.editorconfig`.
