### ISSUE TITLE
Specify dependencies

### ISSUE THREAD

**Issue by zupo** [plone/plone.api#82]
Specify plone.api dependencies based on the "Declaring dependencies" convention.

**Comment by jaroel** [comment]
I've done some work on this in https://github.com/plone/plone.api/tree/plip and will be resolved after the plip.

**Comment by thet** [comment]
great!

**Comment by jaroel** [comment]
I've declared all dependencies that make sense.
Some dependencies are not explicitly specified because they aren't eggs in older Plone/Zope version.
