### ISSUE TITLE
Deprecate api.content.get_uuid()

### ISSUE THREAD

**Issue by zupo** [plone/plone.api#93]
Since Dexterity 2.0, it's now possible to just call context.UID() and get the uuid: https://pypi.python.org/pypi/plone.dexterity

**Comment by zupo** [comment]
That's exactly what we want to avoid. As you need to remember how to adapt context, which utilities to import, from where to import IUUID, etc.

**Comment by pbauer** [comment]
@zupo I don't get the ticket. api.content.get_uuid() does: 

    return IUUID(obj)

what is wrong with that, why should it go away? We dont use 

    obj.UID()

**Comment by zupo** [comment]
The ticket proposes deprecating the api method, as one can now use context.UID() instead. In other words, the api method is superfluous. 

Keep the documentation of how to get the UID in plone.api docs though.

**Comment by pbauer** [comment]
Wow, I misread your first comment (should work on my reading skills). :+1: for deprecating

**Comment by jaroel** [comment]
Ok :)

**Comment by jaroel** [comment]
What needs to be done, and who is going to do it?

**Comment by jensens** [comment]
to late, I would say, people are using this method out in the wild.
